@Restaurants.API_HostAddress = https://localhost:7105
@token = CfDJ8OTqHB-rMAZHu4OWl1BxDwNYXBOjXJ6b69Vrvu-KXYJUHmp8gR9m-skk_HayOrknM5O_ZUHChHc5nr1OBenT3TG_lAuIV8EE8die1xxkBt1IT1QpShq2ZatYKow7J8SXBrVxfFTPy322f8bImc5sdff62BcXxIPmwwJUDNW9cA_yagxEqKtppg1EEm55sFTA-ehHmGZ5BNyr69paKd3liy2LswztDtwhKxcUp13y6FG8aaoJJzRN5C71Kd2XMPPbdXyIKJfZE3NBUs4FbXt4jIvCjc6LcemcbkoI4NU1eVWOQH4Iqb7EpJqIfYVOH573eAA1Xuaf0IGtTbWCa4-bFnH4gvhwkxaQdwPW1HPbDMfoL071Y2rxpSu5WHAqTEQd_Yp-aFajT1BAGAzGubYxHg5AQ_60AmZRkB-F4luEVsCe2Omycm0s7Q0kDg7gCLRww8Evl9grj6CIubl_eXdyz9r4Vhp9anfa26tdtDIPtTZ_HaNdAqKD67UeMjwkinWF6XnflpO6-SGHavmJJ3dqM7stRKxcRsz18kPd4SvjvEanStePI8oHXFx3JdNlJ7n7syU8SszXh46jKNTdpHMsjz5eEzzvk3mg9qc-Cb1WZu6LhL9AC2KoixPdiMHQkQH9rEWMqpASBd0vC8UIr5FG8L5LEX9FcX3eZW4mI_19gQxB7ftT_E_pWcCNbgDELrZbi4VfDrRV1uGbRhtbmahiyX2FAifBGQ9DbRR3mDCp_0sLXRV2qPk-2ahU-QUBayKPcSqmjVHgg8NPNox-wzIWJO7ACZYQ1FsWb9IsTB041ECT
GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=wiza&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}
###
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
##
GET {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "Owner restaurant5",
  "Description": "A dining restaurant specializing in cuisine aroud the world.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@mexi.com",
  "ContactNumber": "555-1212",
  "City": "New York",
  "Street": "132 MEx Street",
  "PostalCode": "10-123"
}

###
GET https://localhost:7105/api/restaurants/4

###
DELETE https://localhost:7105/api/restaurants/14
Authorization: Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/14
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "Updated name",
  "Description": "A indian mexian test dining restaurant the world.",
  "HasDelivery": false
}
###
GET {{Restaurants.API_HostAddress}}/api/restaurants/test

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classica italian past dish with rice meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes/9

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Authorization: Bearer {{token}}
###

@restaurantId=4
@dishId=9
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
@restaurantId=4
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
 "email": "owner2@test.com",
 "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
 "email": "owner@test.com",
 "password": "Password1!"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
 "email": "owner@test.com",
 "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "DateOfBirth":  "2000-01-01",
  "Nationality": "Finnish"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
