@Restaurants.API_HostAddress = https://localhost:7105



GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "The Indian kiss",
  "Description": "A dining restaurant specializing in cuisine aroud the world.",
  "Category": "Indian",
  "HasDelivery": false,
  "ContactEmail": "info@indi.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "222 Main Street",
  "PostalCode": "10-012"
}

###
GET https://localhost:7105/api/restaurants/5