@Restaurants.API_HostAddress = https://localhost:7105
@token = CfDJ8OTqHB-rMAZHu4OWl1BxDwMqY70ajsySQguiNgAgTkvARL0UbMLC9Y3tRcRGlGOZyvLbpBT--labPVXkgFbr7pBdn5t8FQkrlXZmWfJWYjuWXbaZkSOdFIUv_4CdsljvGlUSlMpAXC214x0Hge_MIctKJhmQISHJcQOEzcYnQ_6pWcKtSS72Tnyxb2bziYx3z4XNR8YxSte50cox4P0FMX2eFDSzfXMUcQGnKx7mKyee9BxOu_iTfW234mjCiONgS50Ggxag8l0qNb0SWYh2Ball7licFpiEIyoM_oHDmoEpSMSbu32h0eSWlDUpjBKiWICfG4HZm0pgRF_Bu5F3MoIzfsqEdSEPzsnJSwm0jkuTG8WqdkWhYZDfGzrVvdVXGWKlZXnkzTolS6uXrnQ_nRfbKNgLuFA8-a0K1JXS08q49l0uYzzgjcZ3v670VovKwPqc0VV34WM0OnYEap9blm06Loq9SMt1yFUCh9xYw8edAj3wwoFtKPxl8fKtSEpn53hbFPGq6JBk4u3n0irUtAliyxo8fZN1vCQOmKjs807iVrNG4oUbmR-qHcO8F2_-kgGFqYifX_ZwKMVXEaAUUQwhXonU5dqTTlwDQvA7Vbzp7EBbmH9mN5wfPBLKmGHkgoZFhhN25k7KvVfBA3kFv5EcDmlfgNm3lqFVOuAvqac9Q9qb1YTKXe2FbwZJzHzkeuWA1fp2efNkr4e-GBhGT6VLSNJkcv7uUHr0Qd5gFkmWDSGH4v0AEy_y4RzsvvyksJJ0k3ujiqjCcWAOPgjKMgg

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "The Test hug33",
  "Description": "A dining restaurant specializing in cuisine aroud the world.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@mexi.com",
  "ContactNumber": "555-1212",
  "City": "New York",
  "Street": "132 MEx Street",
  "PostalCode": "10-123"
}

###
GET https://localhost:7105/api/restaurants/4

###
DELETE https://localhost:7105/api/restaurants/3

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/12
Content-Type: application/json

{
  "Name": "A sample patch 8",
  "Description": "A indian mexian test dining restaurant the world.",
  "HasDelivery": false
}
###
GET {{Restaurants.API_HostAddress}}/api/restaurants/test

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classica italian past dish with rice meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes/9

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes

###

@restaurantId=4
@dishId=9
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
@restaurantId=4
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
 "email": "testuser@test.com",
 "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
 "email": "testuser@test.com",
 "password": "Password1!"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
 "email": "owner@test.com",
 "password": "Password1!"
}