@Restaurants.API_HostAddress = https://localhost:7105
@token = CfDJ8OTqHB-rMAZHu4OWl1BxDwODrWx4m2xsuZJ1Ii7cMjVsLFaf5cGTexLnaWvhKhiWAcG2pFPagod9aQ72qVqeAq5rxR6jkRi1oQ21fJBABiPRVstGpBQEt9rNrlT3NIk06tsfmp2fwmGKpKziyxdk_5wH_SYliE4YGv5B7Y29AAnh5nzaDx0LSwUvzksf5ZbySlkWNxRfZ0s7DSUOqOoM18P5779eIVT3gAoNtTP7J9Wkt8S86hFnIsPssIOMM-cfgGo2hUI3ZHlsnw0YBc0ZTQgfcHL_VXIjo09Vh24KjpxfPzabvEX39Uc0Xjvu8LSNtwACrGN7zW7X_tm5KeqqBO8fDc5GAsF9FjkHnfXzIfNEq-OyWFXGizGuIquKbJQEq9pmtfCjPS_JiYpNwcEhM2GlMvFbacBPQVeBVUgmvgu8JhQpTNAhFfnzFQbTj1CxJme4qydIsMMa3aH-V18zvlyWm8stuy_Gw1I1yftKlEJiJ52ENzlXGBPGRBJ9MxiwB5i9tzUXj7uKHTXXAvoOR-ZHOqa_QDTtxdasJ_e8JXUo9gkokUmF8IrUfiZHSGXade0uf9INASCBBuVEhcMmWvjZDslFQgEevSnHM79YKVPqQxZDyrJYp3dXdbnG4YCrlwA6GpuIf7pYhVK3oRaSQQjugLgg3Qcc1X-S1wptshUrOiemRCTFtmKA1ApYv6ZlbfVTj7jJio3d3Sdkx9Jgsmzq8yFisKMfzpT8w-bNJBVJQ_w4OOZJ4IRi56QH17eVIdR9YGY4SldEq3RYTMRtzEmjlGuD0vceF4ozTv6ukkpx

GET {{Restaurants.API_HostAddress}}/api/restaurants
#Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/5

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "The Test hug33",
  "Description": "A dining restaurant specializing in cuisine aroud the world.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@mexi.com",
  "ContactNumber": "555-1212",
  "City": "New York",
  "Street": "132 MEx Street",
  "PostalCode": "10-123"
}

###
GET https://localhost:7105/api/restaurants/4

###
DELETE https://localhost:7105/api/restaurants/3

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/12
Content-Type: application/json

{
  "Name": "A sample patch 8",
  "Description": "A indian mexian test dining restaurant the world.",
  "HasDelivery": false
}
###
GET {{Restaurants.API_HostAddress}}/api/restaurants/test

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classica italian past dish with rice meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes/9

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes

###

@restaurantId=4
@dishId=9
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
@restaurantId=4
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
 "email": "testuser@test.com",
 "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
 "email": "owner@test.com",
 "password": "Password1!"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
 "email": "owner@test.com",
 "password": "Password1!"
}